function(wss_add_example name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE wss::wss)
    wss_set_warnings(${name})
endfunction()

wss_add_example(basic_pool)
wss_add_example(task_handle)
wss_add_example(priority_tasks)
wss_add_example(thread_per_core)
wss_add_example(fair_scheduler)
